export class TourModel {
    company: string;
    country: string;
    province: string;
    city: string;
    id: string;
    name: string;
    description: string;
    category: string;
    subcategories: string;
    saleprice: number;
    type: string;
    duration: string;
    bookingPeriod: string;
    // tslint:disable-next-line:variable-name
    min_people: string;
    // tslint:disable-next-line:variable-name
    max_people: string;
    // tslint:disable-next-line:variable-name
    t_inclued: string;
    // tslint:disable-next-line:variable-name
    t_exclude: string;
    // tslint:disable-next-line:variable-name
    t_highlight: string;
    faq: {};
    program: string;
    featureimage: string;
    language: string;
    moreDetails: {};
    orgdatetime: string;
    date: string;
    time: string;
    status: string;
    posteby: string;
    discountItem: number;
    discountType: string;
}
