export const serviceConfig = {
    // backend-easisec
      registrationUrl: 'global-service/add',
      sendEmailUrl: 'service/send-email',
      getListUrl: 'global-service/list',
      deleteListUrl: 'global-service/remove',
      postDataInsertUrl: 'global-service/add',
      UploadNewImageUrl: 'upload/new',
      downloadDocumentUrl: 'download/',
      loginUrl: 'user/login',
};
export const databaseConfig = {
      dbName: 'easitour',
      dbName2: 'bidoffice',
      tbLocation: 'location',
      tbUtility: 'utility',
      tbProduct: 'product',
      tbDestination: 'destination',
      tbPrivilegeUser: 'UserPrivilegeModel',
      tbAssignCat_product: 'productcat',
      tbTour: 'item',
      tbDTour: 'dtour',
      tbPricingSetting: 'item',
      tbItempriceSetting: 'ItempriceSetting',
      tbTourSlot: 'itemslot',
      tbTourLanguage: 'itemlanguage',
      tbTourCategory: 'itemcategory',
      tbTourSubCategory: 'itemsubcategory',
      tbTourCalendar: 'TourCalendar',
      tbTourContact: 'TourContact',
      tbItemContact: 'itemContact',
      tbtbTourLocation: 'Tourlocation',
      tbUser: 'ETuser',
      tbUserLocation: 'ETuserLocation',
      tbMember: 'member',
      tbMenus: 'menustabs',
      tbRole: 'Role',
      tbPhotogallery: 'photo_gallery',
      tbUserDocument: 'userdocument',
      tbbookinginvoice: 'bookinginvoice',
      tbnewbooking: 'booking',
      tbbookingMain: 'bookingMain',
      tbbookingtraveler: 'bookingtraveler',
      tbcustomerbooking: 'customerbooking',
      tbContinent: 'tbcontinent',
};
export const PayFastAPI = {
    merchant_id: 11495265,
    merchant_key: 'ysjhtlz3zhhld',
    production : true,
    cancel_url : 'https://cloudcalls.easipath.com/',
    return_url : 'https://cloudcalls.easipath.com/',
    notify_url : 'https://cloudcalls.easipath.com/'
};
